name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app:ci -f docker/Dockerfile .

      - name: Run container for test
        run: |
          docker run -d --name test-app -p 8001:8000 my-app:ci
          sleep 5
          curl --fail http://localhost:8001 || exit 1
          docker stop test-app
          docker rm test-app

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          cd ~/devops-lab-service/docker
          git pull origin master
          docker compose up -d --build
