name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app:ci .

      - name: Run container for test
        run: |
          docker run -d --name test-app -p 8000:8000 my-app:ci
          sleep 5
          docker ps | grep test-app
          curl --fail http://localhost:8000 || exit 1
          docker stop test-app
          docker rm test-app
